// COPYRIGHT (C) HARRY CLARK 2025
// STANDALONE REFERENCE UTILITY FOR SIMULATING THE MOTOROLA 68851 MMU

// THIS FILE PERTAINS TOWARDS THE MAIN FUNCTIONALITY OF THE PROGRAM

// SYSTEM INCLUDES

#include <cstdio>

int main(void)
{
    std::printf("HARRY CLARK - M68851 MMU SIMULATOR\n");
    return 0;
}