// COPYRIGHT (C) HARRY CLARK 2025
// STANDALONE REFERENCE UTILITY FOR SIMULATING THE MOTOROLA 68851 MMU

// THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING MEMORY READ AND WRITES
// UTILISING INTRINSIC C++ FEATURES TO DYNAMICALLY HELP WITH MEMORY OPERATIONS

// MORE SPECIFICALLY, THIS FILE AIMS TO PROVIDE MODULARISATION FOR WORKING WITH
// SOME OF THE CORE UTILITY OF THE MMU - WITHOUT CLUTTERING UP OTHER SOURCE FILES

// NESTED INCLUDES  

#include <mmu_mem.hh>
#include <mmu_def.hh>
#include <util.hh>

using namespace aquinas;
using namespace aquinas::mmu_mem;
using namespace aquinas::mmu_mem_opts;

void MEMORY_MANAGER::MEM_TRACE(MEMORY_OPTION OP, U32 ADDRESS, 
                            MEMORY_SIZE SIZE, U32 VALUE) const
{

}

void MEMORY_MANAGER::VERBOSE_TRACE(const std::string& MSG) const
{
    
}